logging:
  level:
    root: INFO
    notificationservice.kafkademo.notificationservice: DEBUG

  file:
    name: logs/notificationservice.log
    max-size: 10MB
    max-history: 30

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

loggers:
  error:
    file:
      name: logs/error-notificationservice.log
      max-size: 10MB
      max-history: 30
      pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
